name: Automated test
on:
  push:
    branches:
      - main
jobs:
  auto_test:
    name: Auto test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Produce actual1.txt output and compare file with 10 numbers
        run: |
          python3 find_lowest_number/find_lowest_number.py find_lowest_number/numbers.txt actual1.txt
          diff testdata/test1_expected.txt actual1.txt

      - name: Produce actual2.txt output and compare file with 1 number
        run: |
          python3 find_lowest_number/find_lowest_number.py testdata/test2_input.txt actual2.txt
          diff testdata/test2_expected.txt actual2.txt
            
      - name: Produce actual3.txt output and compare file with no numbers
        run: |
          python3 find_lowest_number/find_lowest_number.py testdata/test3_input.txt actual3.txt
          diff testdata/test3_expected.txt actual3.txt
