name: Automated test
on: [push]
jobs:
  auto_test:
    name: Auto test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name: Run test
        run: |
          python3 find_lowest_number.py find_lowest_number/numbers.txt > output.txt
          diff output.txt find_lowest_number/expected_output.txt
        
